

services:
  # Service PostgreSQL
  postgres:
    image: postgres:14
    container_name: product-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - product-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Service Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: product-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_HOST=postgres
      - DB_NAME=mydatabase
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=mydatabase;Username=myuser;Password=mypassword
    ports:
      - "5001:8080"
    networks:
      - product-network

  # Service Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: product-ui
    depends_on:
      - backend
    ports:
      - "5002:80"
    networks:
      - product-network
    environment:
      - API_URL=http://backend:8080 

# Volumes pour la persistance des données
volumes:
  postgres-data:
    name: product-postgres-data

# Réseau pour la communication entre les services
networks:
  product-network:
    name: product-network
    driver: bridge
