name: Deploy to Production

on:
  # Déclenché après la réussite des workflows CI
  workflow_run:
    workflows: ["Backend CI", "Frontend CI"]
    types:
      - completed
    branches: [main, master]
    
  workflow_dispatch:


jobs:
  
  deploy:

      name: Deploy to Production Server
      runs-on: self-hosted
      if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
      
      
      steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy locally
        run: |
          docker compose -f docker-compose.production.yml down
          docker compose -f docker-compose.production.yml pull
          docker compose -f docker-compose.production.yml up -d --build --force-recreate