name: Backend CI

on:
  push:
    branches: [ main, master ]
    paths:
      - 'ProductApp.API/**'
      - 'Dockerfile.backend'
      - '.github/workflows/ci-backend.yml'

jobs:


  test:
    name: Test Backend
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup dotnet  
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: '8.0.x'

      - name: Verify project structure
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          if [ -d "ProductApp.API.Tests" ]; then
            ls -la ProductApp.API.Tests/
          fi

      - name: Restore dependencies
        run: dotnet restore ProductApp.API/ProductApp.API.csproj

      - name: Build
        run: dotnet build ProductApp.API/ProductApp.API.csproj --configuration Release --no-restore

      - name: Run tests
        run: |
          if [ -d "ProductApp.API.Tests" ]; then
            dotnet test ProductApp.API.Tests/ProductApp.API.Tests.csproj --configuration Release --no-build --logger "trx;LogFileName=test-results.trx" --collect:"XPlat Code Coverage" --results-directory ./TestResults
          else
            echo "No test project found for backend"
          fi


      - name: Generate test report
        uses: dorny/test-reporter@v1
        if: always()  
        with:
          name: Backend Tests
          path: 'TestResults/*.trx'
          reporter: dotnet-trx
          fail-on-error: false


      - name: upload Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: backend-test-results
          path: TestResults