name: Backend CI

on:
  push:
    branches: [ main, master ]
    paths:
      - 'ProductApp.API/**'
      - 'Dockerfile.backend'
      - '.github/workflows/ci-backend.yml'

jobs:


  test:
    name: Test Backend
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup dotnet  
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: '8.0.x'

      - name: Verify project structure
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          if [ -d "ProductApp.API.Tests" ]; then
            ls -la ProductApp.API.Tests/
          fi

      - name: Restore dependencies
        working-directory: ./ProductApp.API
        run: dotnet restore

      - name: Build
        working-directory: ./ProductApp.API
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        working-directory: ./ProductApp.API
        run: |
          if [ -f "../ProductApp.API.Tests/ProductApp.API.Tests.csproj" ]; then
            echo "Running backend tests..."
            dotnet test ../ProductApp.API.Tests/ProductApp.API.Tests.csproj \
              --configuration Release \
              --no-build \
              --logger "trx;LogFileName=test-results.trx" \
              --collect:"XPlat Code Coverage" \
              --results-directory ./TestResults
          else
            echo "::warning::Test project not found at ../ProductApp.API.Tests/ProductApp.API.Tests.csproj"
            exit 0
          fi


      - name: Generate test report
        uses: dorny/test-reporter@v1
        if: always()  
        with:
          name: Backend Tests
          path: 'ProductApp.API/TestResults/*.trx'
          reporter: dotnet-trx
          fail-on-error: false


      - name: upload Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: backend-test-results
          path: |
            ProductApp.API/TestResults/*