name: Frontend CI

on:
  push:
    branches: [ main, master ]
    paths:
      - 'ProductApp.Client/**'
      - 'Dockerfile.frontend'
      - 'nginx.conf'
      - '.github/workflows/ci-frontend.yml'

env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      IMAGE_NAME: ${{ vars.DOCKERHUB_USERNAME }}/image-frontend-product
      BUILD_NUMBER: ${{ github.run_number }}

jobs:


  test:
    name: Test Frontend
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup dotnet  
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ProductApp.Client/ProductApp.Client.csproj

      - name: Build
        run: dotnet build ProductApp.Client/ProductApp.Client.csproj --configuration Release --no-restore

      - name: Run tests
        run: |
          if [ -d "ProductApp.Client.Tests" ]; then
            dotnet test ProductApp.Client.Tests/ProductApp.Client.Tests.csproj --configuration Release
          else
            echo "No test project found for frontend"
          fi
    
      - name: Notify Slack about test status 
        uses: act10ns/slack@v2
        if: always()
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}    
          message: >
                ${{ job.status == 'success' && ':white_check_mark: Tests PASSED' || ':x: Tests FAILED' }}
                *Workflow*: ${{ github.workflow }}
                *Repository*: <https://github.com/${{ github.repository }}|${{ github.repository }}>
                *Branch*: ${{ github.ref }}
                *Commit*: <https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{
                github.sha
                }}>     
                Triggered by: ${{ github.actor }}          
                *Details*: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run>



  build-and-push:    
             
        name: Build and Push Docker Image
        runs-on: ubuntu-latest
        needs: test
        steps:

            - name: checkout
              uses: actions/checkout@v4

            - name: login to dockerhub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
               
            - name: build docker image
              id: build
              uses: docker/build-push-action@v4
              with:
                 context: .
                 file: ./Dockerfile.frontend
                 push: true
                 tags: |
                    ${{ env.IMAGE_NAME }}:${{ github.run_number }}
                    ${{ env.IMAGE_NAME }}:latest
                              

            - name: Notify Build Results
              if: always()
              uses: act10ns/slack@v2
              with:
                status: ${{ steps.build.outputs.status || job.status }}
                message: |
                    *Docker Build Results* (${{ job.status }})
                    Image: ${{ env.IMAGE_NAME }}:${{ env.BUILD_NUMBER }}
                    ${{ steps.build.outputs.status == 'failure' && '❌ Build failed!' || ':white_check_mark: Build succeeded!' }}
                    ${{ steps.build.outputs.status == 'failure' && 'Check the workflow run for build errors.' || 'Image successfully pushed to Docker Hub.' }}

